### ISSUE TITLE
i will love to do copywriting for you 

### ISSUE THREAD

**Issue by hamzeyto** [abravodev/epubator#1]
I love your application and would want to contribute to it, I'm not a developer but I am good at copywriting. I would love to make a copywrite for your Readme and make a pull request for you to merge. Your response would be highly appreciated. Also I would like to request if we could communicate via email, so I don't have to create issues. Thank you.

**Comment by abravodev** [comment]
Hello Hamza,

It'd very generous of you to help me with the Readme and I'd be really glad in case you did it. 

For the moment, creating issues and PR's seems enough to me. You can reach me at [Twitter](https://www.twitter.com/abravodev), too.
